functionsDirectory = "/Users/edwardburns/Random Stuff/Portfolio/Web App/ORCA/Website/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "/Users/edwardburns/Random Stuff/Portfolio/Web App/ORCA/Website"
publishOrigin = "config"
functions = "/Users/edwardburns/Random Stuff/Portfolio/Web App/ORCA/Website/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/admin*"

[headers.values]
X-Robots-Tag = "noindex, nofollow"
Cache-Control = "no-store"

[[redirects]]
from = "/admin"
to = "/admin.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin-login"
to = "/admin-login.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]